---
name: CI-CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Conan
        run: |
          python -m pip install conan

      - name: Generate artifacts
        run: |
          conan profile detect
          conan build . --build=missing